### PR TITLE
make bugreport

### PR DESCRIPTION
**Pull request by Oxygemo**

### CODE REVIEW

**Comment by Oxygemo** [comment]
btw i borrowed it from cytrus-re's site. i want consistency.

**Comment by Oxygemo** [comment]
(and changed some examples for things i like :) )

**Comment by Devnol** [comment]
> Gentoo

**Comment by Oxygemo** [comment]
has been there before https://raw.githubusercontent.com/Cytrus-RE/cytrus-re.github.io/master/.github/ISSUE_TEMPLATE/bug.md

**Review by Devnol — APPROVED** [review]
> Gentoo

**Comment by Oxygemo** [comment]
Bro it was there before I don't want to change it, shout at Rexo, not me

**Comment by Oxygemo** [comment]
and since you approved merge

**Comment by Devnol** [comment]
Actually yeah I added it lol

**Comment by Oxygemo** [comment]
no it was rexo. he made the file

**Comment by Oxygemo** [comment]
https://github.com/Cytrus-RE/cytrus-re.github.io/blob/master/.github/ISSUE_TEMPLATE/bug.md

**Comment by Devnol** [comment]
I thought I did. I definitely added the example version 4.2.0

**Comment by Oxygemo** [comment]
and 69 on chromium version

**Pull request merged**
