### PR TITLE
teamMembers: use images stored in our own folder instead of using Dis…

### PR DESCRIPTION
**Pull request by Oxygemo**
cord's images.

Why? If discord's servers are down we can use this as a backup, or if Discord is blocked on the network.

Signed-off-by: Oxygemo <alej0hio2007@gmail.com>

### CODE REVIEW

**Review by Oxygemo — COMMENTED** [review]
lgtm

**Review by Devnol — COMMENTED** [review]
The last image does not load because it was changed and no longer exists in the discordcdn.
Use this image instead https://cdn.discordapp.com/avatars/126321762483830785/2d24cde43a1896ed391e56880c72baa3.png

**Comment by Oxygemo** [comment]
Alright

**Comment by Oxygemo** [comment]
Yeah that's an advantage with using images in a folder.

**Comment by Devnol** [comment]
I know it's an advantage, it was another thing I wanted to do but was lazy to. Once Q changed his pfp and it broke I realised it was an actual problem but I cba to do it because I'm a lazy fuck.

**Review by Oxygemo — COMMENTED** [review]
lgtm :)

**Review by Devnol — COMMENTED** [review]
Hold up, why is Q's pfp a png while Rexo's and mine are webps? Could you please fix that?

**Comment by Devnol** [comment]
Well they all load okay so idrc but for the sake of being a png, I'd rather it be a png. Also webp doesn't work in mobile Safari iirc.

**Comment by Oxygemo** [comment]
Well it was a webp before

**Pull request merged**
