### PR TITLE
teamMemberImages: update Denvol's iamge to use png and not randomised…

### PR DESCRIPTION
**Pull request by Oxygemo**
… image name

I plan on doing this for Rexogamer aswell, but I don't have his profile picture as a png (and without le compression ig). Rexo can you please do me a favour and send me that in my DMs thanks

Signed-off-by: Oxygemo <alej0hio2007@gmail.com>

### CODE REVIEW

**Comment by Rexogamer** [comment]
@Devnol why did you use webp of all things

**Comment by Devnol** [comment]
> @Devnol why did you use webp of all things

I didn't. I couldn't get any other format working

**Comment by Oxygemo** [comment]
Everyone fixed.

**Comment by Oxygemo** [comment]
(note: rexo's pfp is converted using an online converter, as I said, please send me the original one in DMs!!!!!!!! (and dont complain tysm))

**Comment by Rexogamer** [comment]
wdym original one and how would I send it

**Comment by Oxygemo** [comment]
The original source png in my discord DMs.

**Comment by Devnol** [comment]
@Rexogamer final review before we merge?

**Comment by Devnol** [comment]
Aight all good from me

**Comment by Oxygemo** [comment]
I never have bugs in my code so lgtm :)

**Pull request merged**
