### PR TITLE
projectindex: fix not-loading-css bug

### PR DESCRIPTION
**Pull request by Oxygemo**
Signed-off-by: Oxygemo <alej0hio2007@gmail.com>

### CODE REVIEW

**Comment by Oxygemo** [comment]
Please merge as fast as I rush B, this looks super ugly. I'm pretty sure it'll fix the issue. it looks like this now for reference 
bilde

**Comment by Devnol** [comment]
rofl it's not a bug, that page was just under construction and I cba to have fixed it by now. I was going to fix it once I was going to work on the page for real.

**Comment by Oxygemo** [comment]
Well I did the work for you.

**Comment by Devnol** [comment]
well yes

**Comment by Oxygemo** [comment]
And yep, that fixed it. ~~now let me in rexo!!!!!~~

**Comment by Oxygemo** [comment]
> rofl it's not a bug
wait are you Todd Howard?

**Pull request merged**
