### PR TITLE
Change rexo's name and use twitter profile instead

### PR DESCRIPTION
**Pull request by Oxygemo**
It's a bit more professional IMO. Rexowogamer to a newcomer would sound a bit off (unless they're like him)

If you would like to, you can discuss why it's great it's like that, but atm I don't see a really good point to having it like that.

### CODE REVIEW

**Comment by Rexogamer** [comment]
"unless they're like him"

it's my discord username which I think makes more sense to most people, also using the Twitter pfp with the github name on a somewhat discord focused site is... yeah

**Comment by Devnol** [comment]
the site isn't necessarily Discord focused?

**Comment by Rexogamer** [comment]
sure but our major projects rn are the bots

**Comment by Oxygemo** [comment]
what i did mean is that new people looking at tts might just leave because it seems quite unprofessional, i recommend you merge.

**Pull request closed without merging**
