### PR TITLE
index: set metadata and embed stuff

### PR DESCRIPTION
**Pull request by Oxygemo**
This makes a nice embed and also fixes edge/ie views (because apparently without my fix it wont work, can't test because I disabled edge and IE from my install :dab:)

### CODE REVIEW

**Comment by Oxygemo** [comment]
I'd also like to thank @Baconz2 for her site containing this (so I could use it for my personal sites, hehe) (but no, proper credits!!)

**Comment by Oxygemo** [comment]
And also I properly commented what they do, so you aren't left confused.

**Comment by Baconz2** [comment]
you're welcome

**Comment by Oxygemo** [comment]
Thanks, you too :)

**Pull request merged**
