### PR TITLE
index: mobile under construction page improvements

### PR DESCRIPTION
**Pull request by Oxygemo**

### CODE REVIEW

**Comment by Oxygemo** [comment]
image
Might be controversial

**Comment by Oxygemo** [comment]
btw Midou please keep gender neutral words here ty

**Comment by Devnol** [comment]
lgtm, rexo go look at it if you want

**Comment by Oxygemo** [comment]
Its lgtm to me

**Comment by Oxygemo** [comment]
gif

**Comment by Oxygemo** [comment]
bump

**Pull request merged**
